---
title: "Data Visualization"
author: "Cherry Pham"
date: "2023-07-06"
output: html_document
---

[Markdown file docstrings]

## INITAL SETTINGS

```{r setup, include=FALSE}
# Check and install required packages if necessary
packages <- c(
  "lubridate",   # Package for working with dates and times
  "data.table",  # Package for efficient data manipulation and processing
  "dplyr",       # Package for data manipulation and transformation
  "openair",     # Package for analyzing air pollution data
  "openairmaps", # Package for accessing open air pollution data
  "stringr",     # Package for string manipulation
  "baseline",    # Package for baseline modeling and adjustment
  "purrr",       # Package for functional programming
  "tidyverse",   # Meta-package for data science
  "maps",        # Package for creating maps
  "wesanderson"
)
install.packages(packages[!sapply(packages, requireNamespace, quietly = TRUE)])

# Load required packages for data manipulation and analysis
invisible(sapply(packages, library, character.only = TRUE))

# Set options
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

# Suppress Warnings (This is a me thing, comment this session out to see the conflicting functions)
suppressPackageStartupMessages(library(maps))
```

## GRAPHING

### Graph 1

Create a time series plot in r comparing bus/train arrival times to pollutant concentration, filtered for wind speed and/or direction

```{r}
# # Merge the datasets based on the timestamp column
# merged_data <- merge(arrival_times, pollutant_data, by = "timestamp", all = TRUE)
# 
# # Filter the merged data based on wind speed and/or direction
# filtered_data <- merged_data %>%
#   filter(wind_speed > threshold_value)
# 
# # Time series comparing bus/train arrival times to pollutant concentration
# ggplot(filtered_data, aes(x = timestamp)) +
#   geom_line(aes(y = arrival_times, color = "Arrival Times")) +
#   geom_line(aes(y = pollutant_concentration, color = "Pollutant Concentration")) +
#   labs(x = "Timestamp", y = "Values") +
#   scale_color_manual(values = c("Arrival Times" = "blue", "Pollutant Concentration" = "red")) +
#   theme_minimal()
#   gc()
```
